{
  "hash": "6518f494ec5892eb905ba8c50139bf85",
  "result": {
    "markdown": "---\ntitle: \"Code of the statistical analysis for the article 'Life Beyond A Jar: Effects of Tank Size and Enrichment on the Behaviour and Welfare of Siamese Fighting Fishes'\"\ndate: \"2024-04-15\"\nauthor: \"Juliette Tariel-Adam\"\nformat: \n   html:\n    embed-resources: true\n    self-contained-math: true\neditor_options: \n  chunk_output_type: console\nknitr:\n  opts_chunk:\n    fig-align: center\n    out-width: \"100%\"\n---\n\n\n\n\nThe script contains the code of data transformation, analysis and graphs for the article \"Life Beyond A Jar: Effects of Tank Size and Enrichment on the Behaviour and Welfare of Siamese Fighting Fishes\" by XXauthorsXXX. It is in two versions: the raw R script in qmd format and the code output in html format. \n\nThe goal was to test the effect of tank enrichment and size on Siamese fish behaviour. The tanks Jar, Small, Medium and Large are compared among each other, and the tank Large and Barren between each other. Barren is not compared to Jar, Small or Medium because they differ by two factors: enrichment and size. \n\nOn the html version of the code, you fill find below a first row of tabs to click on (PCA, Swimming, etc) and for most of these tabs, a second row of tabs to click on (Distribution, Plot, etc).\n\n::: {.panel-tabset}\n\n# Data description\n\nAfter staying 3-7 days in a tank, the behaviour of all fish were scored by four 10-min trials in their tank. All trials occurred on the same day at 4 different times (7 am, 10 am, 2 pm, 6 pm). During the 10 min trial = 600 sec, the fish's behaviour was assigned to one of the 10 behaviours, meaning that the behaviours are mutually exclusive (for instance, a fish can't be scored as nest building and interacting with the surface at the same time): Resting, Swimming, Hovering, Sinking/Floating, Stereotypic swimming, Nest building, Foraging, Interation with surface, Out of view, Unsure. Unsure is not present in the raw dataset.\nOut.of.view is a bit special because it is not a behaviour and was not analysed.\nSinking/Floating was not analysed (see explanation in the PCA section).\n\n::: {.panel-tabset}\n\n## Basic description\n\nThe data has been inspected and corrected for data entry errors (sum of scored behaviours too low/high, column shifted, typos, inconsistent nb of observations per fish/time/tank...).\n\nEach row represents a trial. For each trial, there is:\n+ Fish: the fish tested\n+ Tank: in which tank the fish was\n+ Order: the tank order, i.e. whether it was the first, second, ..., fifth tank that the fish experienced.\n+ Time: time of the day at which the trial happened\n+ Filter: where there a filter in the tank\n+ Behavioural columns. The columns for the behaviours are the time spent doing the specific behaviour in seconds during the trial. Some behaviours (Forgaging, Hovering, Interaction.with.Surface, Stereotypic.swimming) have been trasnformed in binary variable (.bin). The columns .bins represents if the fish performed the specific behaviour at all during the trial or not. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Fish         Tank        Order             Time          Filter   \n Elf    : 20   Jar   :48   Min.   :1.000   7:00 AM :63   No-filter:180  \n Fairy  : 20   Small :52   1st Qu.:2.000   10:00 AM:63   Filter   : 72  \n Ghost  : 20   Medium:52   Median :3.000   2:00 PM :63                  \n Goblin : 20   Large :52   Mean   :2.968   6:00 PM :63                  \n Kinara : 20   Barren:48   3rd Qu.:4.000                                \n Kraken : 20               Max.   :5.000                                \n (Other):132                                                            \n    Swimming        Resting          Hovering      Stereotypic.swimming\n Min.   :  0.0   Min.   :  0.00   Min.   :  0.00   Min.   :  0.00      \n 1st Qu.:133.9   1st Qu.: 92.33   1st Qu.:  6.01   1st Qu.:  0.00      \n Median :224.8   Median :190.99   Median : 23.71   Median :  0.00      \n Mean   :224.6   Mean   :226.04   Mean   : 42.93   Mean   : 42.47      \n 3rd Qu.:309.2   3rd Qu.:354.97   3rd Qu.: 56.21   3rd Qu.: 20.58      \n Max.   :486.8   Max.   :600.00   Max.   :344.27   Max.   :549.00      \n                                                                       \n Nest.building       Foraging      Interation.with.surface Foraging.bin\n Min.   :  0.00   Min.   :  0.00   Min.   :  0.000         No :168     \n 1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:  0.000         Yes: 84     \n Median :  0.00   Median :  0.00   Median :  1.545                     \n Mean   : 33.72   Mean   :  7.83   Mean   : 15.331                     \n 3rd Qu.:  0.00   3rd Qu.:  7.80   3rd Qu.: 14.117                     \n Max.   :512.99   Max.   :125.28   Max.   :251.000                     \n                                                                       \n SS.bin    Hovering.bin Interacting.bin Nest.bin \n No :172   No : 48      No :125         No :201  \n Yes: 80   Yes:204      Yes:127         Yes: 51  \n                                                 \n                                                 \n                                                 \n                                                 \n                                                 \n```\n:::\n\n```{.r .cell-code}\n# Number of observations per fish per tank\ndata %>% group_by(Fish, Tank) %>%\n  summarise(n=n(), .groups = 'drop') %>%\n  spread(Tank,n) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 13 × 6\n   Fish            Jar Small Medium Large Barren\n   <fct>         <int> <int>  <int> <int>  <int>\n 1 Dragon           NA     4      4     4      4\n 2 Elf               4     4      4     4      4\n 3 Fairy             4     4      4     4      4\n 4 Ghost             4     4      4     4      4\n 5 Goblin            4     4      4     4      4\n 6 Kinara            4     4      4     4      4\n 7 Kraken            4     4      4     4      4\n 8 Merlion           4     4      4     4     NA\n 9 Naga              4     4      4     4      4\n10 Orange Pendek     4     4      4     4      4\n11 Pegasus           4     4      4     4      4\n12 Phoenix           4     4      4     4      4\n13 Wizard            4     4      4     4      4\n```\n:::\n\n```{.r .cell-code}\n# Number of observations per fish per time\ndata %>% group_by(Fish, Time) %>%\n  summarise(n=n(), .groups = 'drop') %>%\n  spread(Time,n) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 13 × 5\n   Fish          `7:00 AM` `10:00 AM` `2:00 PM` `6:00 PM`\n   <fct>             <int>      <int>     <int>     <int>\n 1 Dragon                4          4         4         4\n 2 Elf                   5          5         5         5\n 3 Fairy                 5          5         5         5\n 4 Ghost                 5          5         5         5\n 5 Goblin                5          5         5         5\n 6 Kinara                5          5         5         5\n 7 Kraken                5          5         5         5\n 8 Merlion               4          4         4         4\n 9 Naga                  5          5         5         5\n10 Orange Pendek         5          5         5         5\n11 Pegasus               5          5         5         5\n12 Phoenix               5          5         5         5\n13 Wizard                5          5         5         5\n```\n:::\n\n```{.r .cell-code}\n# Sum of all behaviours per trial\ndata3$total <- rowSums(dplyr::select(data3, beh.cols3)) \nsort(data3$total) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1] 556.750 557.010 559.290 571.820 575.700 583.180 584.820 586.990 588.230\n [10] 588.970 592.550 592.810 592.910 593.320 594.830 595.190 595.330 595.560\n [19] 595.760 595.990 596.190 596.270 596.290 596.500 596.600 596.890 596.910\n [28] 597.288 597.370 597.490 597.610 597.700 597.770 597.830 597.890 598.070\n [37] 598.350 598.470 598.480 598.500 598.640 598.730 598.750 599.060 599.560\n [46] 599.580 599.640 599.720 599.810 600.000 600.000 600.040 600.090 600.290\n [55] 600.400 600.410 600.440 600.610 600.620 600.750 600.780 600.880 600.930\n [64] 601.030 601.050 601.070 601.110 601.300 601.360 601.380 601.470 601.550\n [73] 601.560 601.570 601.630 601.650 601.650 601.670 601.680 601.710 601.750\n [82] 601.770 601.810 601.820 601.820 601.860 601.870 601.960 601.970 602.050\n [91] 602.050 602.060 602.060 602.090 602.090 602.110 602.130 602.160 602.160\n[100] 602.170 602.210 602.220 602.370 602.430 602.430 602.450 602.470 602.620\n[109] 602.620 602.640 602.660 602.670 602.710 602.740 602.760 602.760 602.790\n[118] 602.790 602.870 602.900 602.920 602.960 602.970 602.990 603.000 603.010\n[127] 603.100 603.120 603.120 603.170 603.190 603.220 603.220 603.250 603.290\n[136] 603.290 603.310 603.360 603.370 603.380 603.390 603.400 603.410 603.450\n[145] 603.490 603.520 603.650 603.670 603.690 603.690 603.700 603.720 603.730\n[154] 603.800 603.820 603.840 603.880 603.880 603.890 603.910 603.940 604.010\n[163] 604.010 604.020 604.040 604.110 604.120 604.130 604.130 604.190 604.200\n[172] 604.210 604.230 604.260 604.300 604.300 604.310 604.320 604.350 604.360\n[181] 604.360 604.380 604.380 604.400 604.410 604.410 604.430 604.470 604.520\n[190] 604.550 604.590 604.610 604.640 604.660 604.660 604.670 604.670 604.680\n[199] 604.690 604.710 604.720 604.730 604.750 604.780 604.790 604.810 604.870\n[208] 604.890 604.900 604.930 604.930 604.950 604.960 605.000 605.000 605.010\n[217] 605.030 605.060 605.280 605.290 605.310 605.330 605.470 605.470 605.570\n[226] 605.650 605.780 605.830 605.910 605.980 606.000 606.150 606.360 607.020\n[235] 607.170 607.680 607.700 608.260 608.540 608.810 609.200 609.340 609.450\n[244] 610.030 610.130 612.490 612.530 614.340 614.850 616.970 622.480 624.680\n```\n:::\n:::\n\n\nThe sum of all behaviours is not exactly 600 sec (as Unsure is not in the dataset).\n\n\n## Plots\n\nThe mean value over multiple trials is plotted to only have one value per tank and per behaviour. \n\n\n::: {.cell .column-page layout-align=\"center\"}\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-3-2.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-3-3.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-3-4.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-3-5.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-3-6.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Filter\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# nb of fish had a filter in their tank\ntable(data$Tank, data$Filter)/4 \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        \n         No-filter Filter\n  Jar           12      0\n  Small         13      0\n  Medium         7      6\n  Large          7      6\n  Barren         6      6\n```\n:::\n\n```{.r .cell-code}\n# nb of times each fish had a filter in their tank\ntable(data$Fish, data$Filter)/4 \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               \n                No-filter Filter\n  Dragon                1      3\n  Elf                   5      0\n  Fairy                 2      3\n  Ghost                 2      3\n  Goblin                5      0\n  Kinara                5      0\n  Kraken                2      3\n  Merlion               4      0\n  Naga                  5      0\n  Orange Pendek         5      0\n  Pegasus               5      0\n  Phoenix               2      3\n  Wizard                2      3\n```\n:::\n\n```{.r .cell-code}\nplot1(\"Filter\", main = data3, beh_cols = beh.cols3, palette = palette.beh3)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThere have never been a filter in Jar or Small. Some fish never had a filter in their tank. Filter needs to be included in all models as a control variable.\n\n::: \n\n# PCA\n\nWe run a PCA in order to:\n\n+ Try to reduce the number of variables to analyse \n+ Determine which behaviours were important to explain the variability between trials\n+ See correlations between behaviours\n\nThe PCA did not help reduce the number of variables to analyse (see Analysis_PCA.html for more explanation) so the behaviours were analysed separately with linear models. The advantage of separate linear models compared to the PCA is the possibility to quantitatively interpret the differences between tanks.\n\nEven if we did not use PCA for further analysis, the first 4 components are plotted below, which explained 71% of variance in the data, to show the important variables and the correlations between variables. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(pca, choix = \"var\") + labs(title = NULL)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplot(pca, choix = \"var\", axes = c(3,4)) + labs(title = NULL)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-5-2.png){fig-align='center' width=100%}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Contribution to each principal component\nround(pca$var$cos2,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                        Dim.1 Dim.2 Dim.3 Dim.4\nSwimming                 0.68  0.01  0.10  0.00\nResting                  0.80  0.00  0.14  0.04\nHovering                 0.00  0.51  0.04  0.11\nStereotypic.swimming     0.06  0.52  0.13  0.23\nNest.building            0.01  0.06  0.57  0.19\nForaging                 0.32  0.01  0.16  0.18\nInteration.with.surface  0.09  0.16  0.05  0.21\nSinking.Floating         0.06  0.00  0.03  0.18\n```\n:::\n\n```{.r .cell-code}\n# Extent to which each behavioural type contributes to the total variance explained by the first 3 components\nrowSums(pca$var$contrib[,1:3])/3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Swimming                 Resting                Hovering \n              13.946992               17.017016               14.360858 \n   Stereotypic.swimming           Nest.building                Foraging \n              18.372673               17.241361               10.134302 \nInteration.with.surface        Sinking.Floating \n               7.115428                1.811372 \n```\n:::\n:::\n\n\n+ The 1st PCA component was driven by Resting (cos2 = 0.8), Swimming (0.7) and Foraging (0.3). Swimming and Foraging opposite to Resting. This first component could be interpret as \"activity\". If a fish spent a lot of time swimming and foraging during a trial, it was very little resting. This first component explained 25% of the variance in the data (as a reminder, the data is the time spent performing the different types of behaviour). So 1 quarter of the variance is a matter of activity. Keep in mind for the rest of the analyses that these behavioural types are correlated. \n\n+ The 2nd PCA component was driven by Hovering (cos2 = 0.5) and Stereotypic.swimming (0.5), and a bit by Interaction with surface (0.16). Hovering and Interacting.with.Surface opposite to Stereotypic.swimming. If the fish spent a lot of time hovering (and interacting with the surface), it was very little stereotypic swimming.\n\n+ The 3rd PCA component was driven mainly by Nest building (cos2 = 0.6), and a bit by Foraging (0.16), Resting (0.14) and Stereotypic Swimming (0.13). Foraging and Resting opposite to Nest building and Stereotypic Swimming. If a fish spent time foraging and resting in a trial, it was little nest building and stereotypic swimming. This makes sense, it a fish is building a nest,it is an important task and needs to be finished, so it is not scattering its time with other activities. The apparent correlation between nest building and stereotypic swimming could be due to Jar where fish in this tank rarely engaged in nest building or stereotypic swimming. \n\n+ The 4th PCA component was not easily interpretable = not easily linked to the initial behavioural variables.\n\nSinking/Floating contributed almost nothing to the PCA (1.8%) + did not correlate strongly with any of the component. Sinking/Floating was not important to explain the variability between trials. We did not further analyse this behaviour.\n\n# Swimming\n\n::: {.panel-tabset}\n\n## Distribution \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist1(data$Swimming)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Plot \n\nThe first plot is to see the trend by tank. Big red dots is for the overall mean  by tank. Small black points are raw data = swimming time of each trial. \n\nThe second plot is to see the trend by fish and by tank. The dashed black line is means by tank. The other lines are the means for each fish by tank. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_var(data, \"Swimming\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplot_var_fish(data, \"Swimming\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-8-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Linear model \n\n\n::: {.cell .column-page layout-align=\"center\"}\n\n```{.r .cell-code}\nmSwimming <- lmer(Swimming ~ Tank + Time + Filter + (1|Fish), data = data)\nanova(mSwimming, ddf = \"Kenward-Roger\", type = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nType II Analysis of Variance Table with Kenward-Roger's method\n       Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    \nTank   240332   60083     4 236.97  10.065 1.535e-07 ***\nTime   337219  112406     3 231.05  18.832 5.812e-11 ***\nFilter 111221  111221     1 151.81  18.633 2.846e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\ncalc_contrasts(mSwimming)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         contrast estimate   SE  df t.ratio p.value lower.CL upper.CL\n1    jar_vs_small      -14 15.5 232   -0.90  >0.999      -56       28\n2   jar_vs_medium      -12 17.4 242   -0.69  >0.999      -59       35\n3    jar_vs_large      -93 17.4 242   -5.31  <0.001     -140      -45\n4 small_vs_medium        2 17.4 243    0.11  >0.999      -45       49\n5  small_vs_large      -79 17.4 243   -4.53  <0.001     -126      -32\n6 medium_vs_large      -81 15.2 231   -5.32  <0.001     -122      -39\n7 large_vs_barren       58 15.5 232    3.76  <0.001       16      101\n```\n:::\n\n```{.r .cell-code}\nemmeans(mSwimming, ~ Time) # estimated means of time spent swimming depending on the time of the day \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Time     emmean   SE   df lower.CL upper.CL\n 7:00 AM     301 14.9 28.9      270      331\n 10:00 AM    243 14.9 28.9      212      273\n 2:00 PM     206 14.9 28.9      176      237\n 6:00 PM     216 14.9 28.9      186      247\n\nResults are averaged over the levels of: Tank, Filter \nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n:::\n\n```{.r .cell-code}\nemmeans(mSwimming, ~ Filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Filter    emmean   SE   df lower.CL upper.CL\n No-filter    202 12.8 15.2      175      229\n Filter       281 17.6 34.4      246      317\n\nResults are averaged over the levels of: Tank, Time \nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n:::\n:::\n\n\nEffect of Tank, Time and Filter! \n\n+ Tank. Large swam significantly more time than Jar, Small and Medium. Fish in Large swan 93 sec [CI 45, 140] more than Jar (over a 600 sec trial), 79 sec [CI 32, 126] more than Small, and 81 sec [CI 39, 122] more than Medium. In addition,  fish in Large swam significantly more time (58 sec [CI 16, 101]) than fish in Barren. \n+ Time. Fish swim more in the morning than in the afternoon, especially at 7 am.\n+ Filter. Fish swim more with a filter in their tank.\n\n## Between-fish diff\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Uncomment the 2 lines below if running the script for the first time\n## rpt.swimming <- rpt(Swimming ~ Tank + Time + Filter + (1|Fish), grname = \"Fish\", data = data, datatype = \"Gaussian\", nboot = 1000, npermut = 1000)\n## save(rpt.swimming, file = \"Script/Repeatability rptR output/rpt.swimming\")\nbase::load(\"Script/Repeatability rptR output/rpt.swimming\")\nsummary(rpt.swimming)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nRepeatability estimation using the lmm method\n\nCall = rpt(formula = Swimming ~ Tank + Time + Filter + (1 | Fish), grname = \"Fish\", data = data, datatype = \"Gaussian\", nboot = 1000, npermut = 1000)\n\nData: 252 observations\n----------------------------------------\n\nFish (13 groups)\n\nRepeatability estimation overview: \n      R     SE   2.5%  97.5% P_permut  LRT_P\n  0.198 0.0802 0.0441  0.352    0.001      0\n\nBootstrapping and Permutation test: \n            N    Mean Median   2.5%  97.5%\nboot     1000 0.19068  0.186 0.0441 0.3520\npermut   1000 0.00981  0.000 0.0000 0.0504\n\nLikelihood ratio test: \nlogLik full model = -1459.844\nlogLik red. model = -1474.76\nD  = 29.8, df = 1, P = 2.35e-08\n\n----------------------------------------\n```\n:::\n:::\n\n\nLikelihood ratio test indicates a statistically significant random effect. Meaning that fish behaved differently among each others in terms of swimming. But the repeatability is quite low (0.2 [95% CI 0.04, 0.35]). \n\n## Diagnosis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm_diagnosis(mSwimming)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"check constant variance over fitted values\"\n```\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Normality of Swimming\"\n```\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-11-2.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Normality random residuals\"\n```\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-11-3.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-11-4.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe model seems good.\n\n:::\n\n# Resting\n\n::: {.panel-tabset}\n\n## Distribution \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist1(data$Resting)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\ntable(data$Resting==0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n  241    11 \n```\n:::\n:::\n\n\nOnly 11 trials where the fish did not rest at all. \n\n## Plot \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_var(data, \"Resting\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplot_var_fish(data, \"Resting\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-13-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Linear model \n\n\n::: {.cell .column-page layout-align=\"center\"}\n\n```{.r .cell-code}\nmResting <- lmer(Resting ~ Tank + Time + Filter + (1|Fish), data = data)\nanova(mResting, ddf = \"Kenward-Roger\", type = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nType II Analysis of Variance Table with Kenward-Roger's method\n       Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    \nTank   547562  136891     4 235.30 10.3044 1.049e-07 ***\nTime   795993  265331     3 231.01 19.9736 1.514e-11 ***\nFilter   9752    9752     1 222.98  0.7341    0.3925    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\ncalc_contrasts(mResting)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         contrast estimate   SE  df t.ratio p.value lower.CL upper.CL\n1    jar_vs_small       46 23.2 232    2.00   0.186      -17      109\n2   jar_vs_medium       -4 26.3 239   -0.16  >0.999      -75       67\n3    jar_vs_large      110 26.3 239    4.19  <0.001       39      181\n4 small_vs_medium      -51 26.2 241   -1.93   0.186     -122       21\n5  small_vs_large       64 26.2 241    2.43   0.080       -8      135\n6 medium_vs_large      114 22.6 231    5.05  <0.001       53      175\n7 large_vs_barren       -5 23.2 231   -0.22  >0.999      -68       58\n```\n:::\n\n```{.r .cell-code}\nemmeans(mResting, ~ Time)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Time     emmean   SE   df lower.CL upper.CL\n 7:00 AM     141 29.1 19.6     80.1      202\n 10:00 AM    199 29.1 19.6    137.8      259\n 2:00 PM     259 29.1 19.6    198.1      320\n 6:00 PM     286 29.1 19.6    225.7      347\n\nResults are averaged over the levels of: Tank, Filter \nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n:::\n:::\n\n\nEffect of Tank and Time.\n\n+ Tank. Large rested significantly less time than Jar and Medium (almost significant for Small). Fish in Large rested 110 sec [CI 39, 181] more than fish in Jar (over a 600 sec trial), and 114 sec [CI 53, 175] more  fish in Medium. This is in line with the PCA and the results of Swimming: Fish that spent time swimming spent less time resting. Fish in Large were overall more active. No significant difference between Large and Barren. \n+ Time. Fish rest less time in the morning, especially at 7 am. In line with the PCA and the results of Swimming.\n\n## Between-fish diff\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Uncomment the 2 lines below if running the script for the first time\n## rpt.resting <- rpt(Resting ~ Tank + Time + Filter + (1|Fish), grname = \"Fish\", data = data, datatype = \"Gaussian\", nboot = 1000, npermut = 1000)\n## save(rpt.resting, file = \"Script/Repeatability rptR output/rpt.resting\")\nbase::load(\"Script/Repeatability rptR output/rpt.resting\")\nsummary(rpt.resting)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nRepeatability estimation using the lmm method\n\nCall = rpt(formula = Resting ~ Tank + Time + Filter + (1 | Fish), grname = \"Fish\", data = data, datatype = \"Gaussian\", nboot = 1000, npermut = 1000)\n\nData: 252 observations\n----------------------------------------\n\nFish (13 groups)\n\nRepeatability estimation overview: \n      R     SE   2.5%  97.5% P_permut  LRT_P\n  0.369  0.106  0.153  0.562    0.001      0\n\nBootstrapping and Permutation test: \n            N    Mean Median   2.5%  97.5%\nboot     1000 0.36078  0.359  0.153 0.5617\npermut   1000 0.00933  0.000  0.000 0.0452\n\nLikelihood ratio test: \nlogLik full model = -1565.567\nlogLik red. model = -1599.854\nD  = 68.6, df = 1, P = 6.1e-17\n\n----------------------------------------\n```\n:::\n:::\n\n\nLikelihood ratio test indicates a statistically significant random effect. Meaning that fish behaved differently among each others in terms of swimming. The repeatability is OK 0.37 [95% CI 0.15, 0.56].\n\n## Diagnosis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm_diagnosis(mResting)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"check constant variance over fitted values\"\n```\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Normality of Resting\"\n```\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-16-2.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Normality random residuals\"\n```\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-16-3.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-16-4.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe model seems good.\n\n## Resting place\n\nJust a plot with the amount of time resting at the different places depending on the tank. Each bar value is the mean of resting times over trials and fish. \n\n\n::: {.cell .column-page layout-align=\"center\"}\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-17-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\nFrom the graphs, we can see that fish use different places to rest, not only one type. They use all the different places available. It does not seem that there is a preferred resting place. \n\n:::\n\n# Hovering\n\n::: {.panel-tabset}\n\n## Distribution \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist1(data$Hovering)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\ntable(data$Hovering==0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n  204    48 \n```\n:::\n\n```{.r .cell-code}\ndescdist(data$Hovering, boot = 1000, print = FALSE)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-18-2.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nquantile(data$Hovering)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    0%    25%    50%    75%   100% \n  0.00   6.01  23.71  56.21 344.27 \n```\n:::\n\n```{.r .cell-code}\nhist1(data$Hovering[data$Hovering!=0]) # histogram without the zeros\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-18-3.png){fig-align='center' width=100%}\n:::\n:::\n\n\nEven if there are less zeros than Foraging or Stereotypic Swimming, it is not a normal distribution. There were only 48 trials (out of 252) during which no hovering happened. So 204 trials where we could study the amount of time hovering in 204 trials. \n\nWe fitted a glm distribution like Foraging and Stereotypic Swimming on the probability to hover (dependent variable is 1 if hovering occurred during the trial, zero otherwise).\n\nTo analyse the amount of time the fish was hovering on the 204 trials with hovering time > 0, we tried different models described in \"Analysis_Hovering\". The best model was a linear mixed model on the amount of time spent hovering with weighted least squares.\n\n## Plot \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Effect of tank of the probability to hover during a trial\nplot_var_binary(data, \"Hovering.bin\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplot_var_binary_fish(data, \"Hovering.bin\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-19-2.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n# Among the trials where the fish hovers, effect of tank on the amount of time hovering\ndata %>% filter(Hovering >0) %>% \n  plot_var(., \"Hovering\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-19-3.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\ndata %>% filter(Hovering >0) %>% \n  plot_var_fish(., \"Hovering\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-19-4.png){fig-align='center' width=100%}\n:::\n:::\n\n\nBoth the probability to hover and the time spent hovering seems to be higher in Jar compared to the others. All fish besides Goblin hovered more in Jar compared to Small.\n\n## Generalised linear model \n\nY variable = probability to hover during a trial\n\n\n::: {.cell .column-page layout-align=\"center\"}\n\n```{.r .cell-code}\nmHovering <- glmmTMB(Hovering.bin ~ Tank + Time + Filter + (1|Fish), data = data, family =binomial)\n\nglmmTMB:::Anova.glmmTMB(mHovering)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table (Type II Wald chisquare tests)\n\nResponse: Hovering.bin\n        Chisq Df Pr(>Chisq)  \nTank   6.8189  4    0.14578  \nTime   9.3478  3    0.02501 *\nFilter 4.3176  1    0.03772 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nemmeans(mHovering, ~ Time, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Time      prob     SE  df asymp.LCL asymp.UCL\n 7:00 AM  0.917 0.0398 Inf     0.798     0.969\n 10:00 AM 0.870 0.0525 Inf     0.729     0.943\n 2:00 PM  0.728 0.0786 Inf     0.551     0.854\n 6:00 PM  0.747 0.0760 Inf     0.573     0.866\n\nResults are averaged over the levels of: Tank, Filter \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n:::\n\n```{.r .cell-code}\nemmeans(mHovering, ~ Filter, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Filter     prob     SE  df asymp.LCL asymp.UCL\n No-filter 0.900 0.0343 Inf     0.810     0.950\n Filter    0.729 0.0933 Inf     0.516     0.872\n\nResults are averaged over the levels of: Tank, Time \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n:::\n:::\n\n\nNo effect of Tank on the probability to hover during a trial, only an effect of Time and filter\n\n+ Time. Fish were less likely to hover in the afternoon.\n+ Filter. Fish were less likely to hover with a filter in their tank.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmHovering_res <- simulateResiduals(mHovering)\nplot(mHovering_res)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe model seems good. \n\n## Linear model\n\nY variable = amount of time spent hovering during a trial. Only trials with hovering time > 0\n\nLinear model with weighted least squares\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmHovering2 <- lme(Hovering ~ Tank + Time + Filter, random = ~1 | Fish, data = data[data$Hovering>0,], weights = varPower(), control = lmeControl(maxIter = 20000))\n\nanova(mHovering2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            numDF denDF  F-value p-value\n(Intercept)     1   183 43.85489  <.0001\nTank            4   183 18.75147  <.0001\nTime            3   183  3.66785  0.0134\nFilter          1   183  5.29132  0.0226\n```\n:::\n\n```{.r .cell-code}\ncalc_contrasts(mHovering2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         contrast estimate   SE  df t.ratio p.value lower.CL upper.CL\n1    jar_vs_small       53 12.0 183    4.40  <0.001       20       85\n2   jar_vs_medium       53 12.0 183    4.42  <0.001       20       86\n3    jar_vs_large       61 11.9 183    5.10  <0.001       28       93\n4 small_vs_medium        1  6.5 183    0.08   0.938      -17       18\n5  small_vs_large        8  6.2 183    1.30   0.394       -9       25\n6 medium_vs_large        8  2.7 183    2.81   0.016        0       15\n7 large_vs_barren      -22  4.9 183   -4.53  <0.001      -35       -9\n```\n:::\n\n```{.r .cell-code}\nemmeans(mHovering2, ~ Time) # estimated means of time spent Hovering depending on the time of the day \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Time     emmean   SE df lower.CL upper.CL\n 7:00 AM    39.3 5.06 12     28.2     50.3\n 10:00 AM   48.3 5.72 12     35.8     60.8\n 2:00 PM    48.1 5.68 12     35.7     60.4\n 6:00 PM    42.4 5.23 12     31.0     53.8\n\nResults are averaged over the levels of: Tank, Filter \nDegrees-of-freedom method: containment \nConfidence level used: 0.95 \n```\n:::\n\n```{.r .cell-code}\nemmeans(mHovering2, ~ Filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Filter    emmean   SE df lower.CL upper.CL\n No-filter   52.2 5.30 12     40.7     63.8\n Filter      36.8 6.53 12     22.5     51.0\n\nResults are averaged over the levels of: Tank, Time \nDegrees-of-freedom method: containment \nConfidence level used: 0.95 \n```\n:::\n:::\n\n\nEffect of Tank, Time and Filter.\n\n+ Tank. Jar hovered significantly more time than Small, Medium and Large. Fish in Jar hovered 53 sec [CI 20, 85] more than Small (over a 600 sec trial), 53 sec [CI 20, 86] more than Medium, and 61 sec [CI 28, 93] more than Large. Fish in medium hovered more time than fish in Large. In addition, fish in Barren hovered significantly more time (22 sec [CI 9, 35]) than fish in Large.\n+ Time. Fish hovered more time in the middle of the day.\n+ Filter. Fish hovered less time with a filter in their tank.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(mHovering2, resid(., type = \"pearson\") ~ fitted(.), aspect = 1, pch = 21, abline = 0)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nqqnorm(resid(mHovering2, type = \"pearson\"))\nqqline(resid(mHovering2, type = \"pearson\"))\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-23-2.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nranefPlot <- ranef(mHovering2, level = 1)\nqqnorm(ranefPlot$`(Intercept)`)\nqqline(ranefPlot$`(Intercept)`)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-23-3.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe model seems good besides the normality. But linear models are robust to the normality assumption (= we can still draw true inference).\n\n## Hovering place\n\nJust a plot with where the fish hovers at the different places depending on the tank.\n\n\n::: {.cell .column-page layout-align=\"center\"}\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-24-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\nFish used different places for hovering in all tanks.\n\n:::\n\n# Foraging\n\n::: {.panel-tabset}\n\n## Distribution \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist1(data$Foraging)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\ntable(data$Foraging==0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n   84   168 \n```\n:::\n\n```{.r .cell-code}\ndescdist(data$Foraging, boot = 1000, print = FALSE)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-25-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe data are clearly not following a normal distribution. It seems that a beta distribution could suit but foraging is not a continuous variable ranging from 0 to 1. Foraging has thus been analysed as a binary variable: 1 if fish spent time foraging during this trial, 0 otherwise.\n\nThere were 168 trials (out of 252) during which no foraging happened.\n\n## Plot \n\nThe plots are in percentage of trials during which the fish foraged over the total number of trials.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_var_binary(data, \"Foraging.bin\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-26-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplot_var_binary_fish(data, \"Foraging.bin\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-26-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Generalised linear model \n\n\n::: {.cell .column-page layout-align=\"center\"}\n\n```{.r .cell-code}\nmForaging <- glmmTMB(Foraging.bin ~ Tank + Time + Filter + (1|Fish), data = data, family =binomial)\n\nglmmTMB:::Anova.glmmTMB(mForaging)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table (Type II Wald chisquare tests)\n\nResponse: Foraging.bin\n         Chisq Df Pr(>Chisq)    \nTank   32.8992  4  1.253e-06 ***\nTime    1.8103  3     0.6127    \nFilter  0.8031  1     0.3702    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\ncalc_contrasts_bin(mForaging)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         contrast odds.ratio   SE  df null z.ratio p.value asymp.LCL asymp.UCL\n1    jar_vs_small       1.88 1.03 Inf    1    1.15   0.251     0.428     8.250\n2   jar_vs_medium       0.29 0.17 Inf    1   -2.07   0.078     0.056     1.459\n3    jar_vs_large       0.08 0.05 Inf    1   -3.97  <0.001     0.014     0.437\n4 small_vs_medium       0.15 0.10 Inf    1   -2.90   0.015     0.027     0.875\n5  small_vs_large       0.04 0.03 Inf    1   -4.63  <0.001     0.006     0.262\n6 medium_vs_large       0.27 0.13 Inf    1   -2.79   0.016     0.076     0.952\n7 large_vs_barren      14.64 7.98 Inf    1    4.92  <0.001     3.378    63.486\n```\n:::\n\n```{.r .cell-code}\n# example of differences between Jar and Large\n## Contrast estimate\n1/0.08\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 12.5\n```\n:::\n\n```{.r .cell-code}\n## Lower CI\n1/0.437\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.28833\n```\n:::\n\n```{.r .cell-code}\n## Upper CI\n1/0.014\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 71.42857\n```\n:::\n:::\n\n\nEffect of Tank. \n\nAs a reminder, an odds.ratio < 1 between tank X vs tank Y means the probability of foraging during a trial in tank X is smaller that the probability of foraging during a trial in tank Y. An odd ratio for instance of 0.2 means that a fish is (1 / 0.2) = five times more likely to forage during a trial in tank Y than in Tank X. If we imagine 5 trials, fish will forage on average during 1 trial out of 5 in Tank X whereas fish will forage on average during 5 trials out of 5 in Tank Y. \n\n+ Tank. Fish were more likely to forage during a trial in Large compared to Jar, Small and Medium. Again in accordance with the PCA and the results of Swimming and Resting. Fish in Large were on average 13 times [CI 2, 71] more likely to forage during a trial than fish in Jar, 25 times [CI 4, 166] than fish in Small, and 4 times [CI 1, 13] than fish in Medium. In addition, fish were 15 times [CI 3, 63] more likely to forage during a trial in Large than Barren. In accordance with the PCA and the results of Swimming. This time, there was also a significant difference between small and medium.\n\n## Between-fish diff\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Attempt to calculate repeatability\nrpt.foraging <- rpt(Foraging.bin ~ Tank + Time + Filter + (1|Fish), grname = \"Fish\", data = data, datatype = \"Binary\", nboot = 0, npermut = 0)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in checkConv(attr(opt, \"derivs\"), opt$par, ctrl = control$checkConv, :\nModel failed to converge with max|grad| = 0.00341065 (tol = 0.002, component 1)\nWarning in checkConv(attr(opt, \"derivs\"), opt$par, ctrl = control$checkConv, :\nModel failed to converge with max|grad| = 0.00341065 (tol = 0.002, component 1)\n```\n:::\n\n```{.r .cell-code}\n# attempt with package glmer rather than glmmTMB\nmForaging2 <- glmer(Foraging.bin ~ Tank + Time + Filter + (1|Fish), data = data, family = \"binomial\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in checkConv(attr(opt, \"derivs\"), opt$par, ctrl = control$checkConv, :\nModel failed to converge with max|grad| = 0.00341065 (tol = 0.002, component 1)\n```\n:::\n\n```{.r .cell-code}\n# Likelihood ratio test of random effect\nmForaging0 <- glmmTMB(Foraging.bin ~ Tank + Time + Filter, data = data, family =binomial)\nanova(mForaging0, mForaging)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData: data\nModels:\nmForaging0: Foraging.bin ~ Tank + Time + Filter, zi=~0, disp=~1\nmForaging: Foraging.bin ~ Tank + Time + Filter + (1 | Fish), zi=~0, disp=~1\n           Df    AIC    BIC  logLik deviance  Chisq Chi Df Pr(>Chisq)    \nmForaging0  9 297.42 329.18 -139.71   279.42                             \nmForaging  10 280.69 315.98 -130.34   260.69 18.734      1  1.503e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nError when calculating the repeatability with rptR. Hard to estimate repeatability on binary data. I don't know how to do it without the package rptR. I think we don't have enough data power anyway to calculate repeatability with a binary variable. I tried to use the lmer package to calculate the repeatability with rptR but the model failed to converge when using glmer().\n\nLikelihood ratio test indicates a statistically significant random effect. Meaning that fish behaved differently among each others in terms of foraging. \n\n## Diagnosis \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmForaging_res <- simulateResiduals(mForaging)\nplot(mForaging_res)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplotResiduals(mForaging_res, form = data$Tank)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-29-2.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplotResiduals(mForaging_res, form = data$Time)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-29-3.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplotResiduals(mForaging_res, form = data$Filter)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-29-4.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe model seems good.\n\n:::\n\n# Stereotypic swimming\n\n::: {.panel-tabset}\n\n## Distribution \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist1(data$Stereotypic.swimming)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\ntable(data$Stereotypic.swimming==0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n   80   172 \n```\n:::\n\n```{.r .cell-code}\ndescdist(data$Stereotypic.swimming, boot = 1000, print = FALSE)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-30-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\nIdem Foraging. Analysis as binary variable if the fish performs stereotypic swimming during a trial or not. \n\nThere were 172 trials (out of 252) during which no stereotypic swimming happened.\n\n## Plot \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(plotSS1 <- plot_var_binary(data, \"SS.bin\"))\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n(plotSS2 <- plot_var_binary_fish(data, \"SS.bin\"))\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-31-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\nHuge variability between fish as always. Some fish never performed stereotypic swimming while some in all tanks. \n\n## Generalised linear model \n\n\n::: {.cell .column-page layout-align=\"center\"}\n\n```{.r .cell-code}\nmSS <- glmmTMB(SS.bin ~ Tank + Time + Filter + (1|Fish), data = data, family =binomial)\n\nglmmTMB:::Anova.glmmTMB(mSS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table (Type II Wald chisquare tests)\n\nResponse: SS.bin\n         Chisq Df Pr(>Chisq)    \nTank   24.6257  4  5.982e-05 ***\nTime    3.0947  3     0.3773    \nFilter  1.1698  1     0.2795    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\ncalc_contrasts_bin(mSS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         contrast odds.ratio   SE  df null z.ratio p.value asymp.LCL asymp.UCL\n1    jar_vs_small       0.03 0.02 Inf    1   -4.56  <0.001     0.003     0.229\n2   jar_vs_medium       0.22 0.21 Inf    1   -1.59   0.284     0.016     2.880\n3    jar_vs_large       0.18 0.18 Inf    1   -1.77   0.284     0.014     2.417\n4 small_vs_medium       7.87 6.78 Inf    1    2.39   0.100     0.775    79.810\n5  small_vs_large       6.60 5.65 Inf    1    2.20   0.138     0.660    66.078\n6 medium_vs_large       0.84 0.50 Inf    1   -0.30   0.767     0.171     4.130\n7 large_vs_barren       0.32 0.20 Inf    1   -1.80   0.284     0.060     1.743\n```\n:::\n:::\n\n\nEffect of Tank. \n\n+ Tank. Jar were less likely to perform stereotypic swimming during a trial than Small/Medium/Large but only significant between Jar and Small. Fish in Small were 33 times [CI 4, 333] more likely to perform stereotypic swimming during a trial than fish in Jar.\n\n## Between-fish diff\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Attempt to calculate repeatability\nrpt.SS <- rpt(SS.bin ~ Tank + Time + Filter + (1|Fish), grname = \"Fish\", data = data, datatype = \"Binary\", nboot = 0, npermut = 0)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in checkConv(attr(opt, \"derivs\"), opt$par, ctrl = control$checkConv, :\nModel failed to converge with max|grad| = 0.00627069 (tol = 0.002, component 1)\nWarning in checkConv(attr(opt, \"derivs\"), opt$par, ctrl = control$checkConv, :\nModel failed to converge with max|grad| = 0.00627069 (tol = 0.002, component 1)\n```\n:::\n\n```{.r .cell-code}\n# attempt with package glmer rather than glmmTMB\nmSS2 <- glmer(SS.bin ~ Tank + Time + Filter + (1|Fish), data = data, family = \"binomial\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in checkConv(attr(opt, \"derivs\"), opt$par, ctrl = control$checkConv, :\nModel failed to converge with max|grad| = 0.00627069 (tol = 0.002, component 1)\n```\n:::\n\n```{.r .cell-code}\n# Likelihood ratio test of random effect\nmSS0 <- glmmTMB(SS.bin ~ Tank + Time + Filter, data = data, family =binomial)\nanova(mSS0, mSS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData: data\nModels:\nmSS0: SS.bin ~ Tank + Time + Filter, zi=~0, disp=~1\nmSS: SS.bin ~ Tank + Time + Filter + (1 | Fish), zi=~0, disp=~1\n     Df    AIC    BIC  logLik deviance  Chisq Chi Df Pr(>Chisq)    \nmSS0  9 277.42 309.19 -129.71   259.42                             \nmSS  10 205.76 241.05  -92.88   185.76 73.661      1  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nError when calculating the repeatability with rptR, idem Foraging. \n\nLikelihood ratio test indicates a statistically significant random effect. Meaning that fish behaved differently among each others in terms of stereotypic swimming. \n\n## Diagnosis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmSS_res <- simulateResiduals(mSS)\nplot(mSS_res)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-34-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplotResiduals(mSS_res, form = data$Tank)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-34-2.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplotResiduals(mSS_res, form = data$Time)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-34-3.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplotResiduals(mSS_res, form = data$Filter)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-34-4.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n# Problem with Filter, I retried the model without Filter\nmSS2 <- glmmTMB(SS.bin ~ Tank + Time + (1|Fish), data = data, family =binomial)\nplot(simulateResiduals(mSS2))\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-34-5.png){fig-align='center' width=100%}\n:::\n:::\n\n\nIt is expected to have a problem with filter as there are more than twice more trials without filter than with filter. No problem when removing Filter from the model. The model seems good.\n\n## Stereotypic types\n\nJust a plot with the type of stereotypic swimming depending on the tank. To stick with the analysis, it is a count (count = 1 if the fish performs a certain type of stereotypic swimming during a trial). \n\n\n::: {.cell .column-page layout-align=\"center\"}\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-35-1.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-35-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\nIt seems that there are not differences between tanks. Just circles seem specific to larger tanks (Medium/Large/Barren).\n\n## Stereotypic Swimming repetitions\n\n\n::: {.cell .column-page layout-align=\"center\"}\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n     Tank          Fish     Time Stereotypic.swimming.type Nb.rep\n1   Small        Dragon  7:00 AM                    Pacing    328\n2   Small        Dragon 10:00 AM                    Pacing     76\n3   Small        Dragon  2:00 PM                    Pacing     20\n4   Small        Dragon  6:00 PM                    Pacing      8\n5   Small        Dragon  6:00 PM         Pacing front wall      8\n6  Barren        Dragon  7:00 AM                    Pacing      4\n7  Barren        Dragon 10:00 AM                    Pacing      5\n8  Barren        Dragon  2:00 PM                    Pacing     19\n9  Barren        Dragon  6:00 PM                    Pacing      4\n10    Jar           Elf  7:00 AM                   Zig zag      4\n11    Jar           Elf  6:00 PM                   Zig zag      6\n12  Small           Elf  7:00 AM                    Pacing     15\n13  Small           Elf 10:00 AM                    Pacing     15\n14  Small           Elf  2:00 PM                    Pacing    109\n15  Small           Elf  6:00 PM                    Pacing     25\n16 Medium           Elf  7:00 AM                    Pacing      4\n17 Medium           Elf 10:00 AM                    Pacing     34\n18 Medium           Elf  2:00 PM                    Pacing     14\n19  Large           Elf 10:00 AM                   Circles     12\n20  Large           Elf 10:00 AM                    Pacing      8\n21 Barren           Elf  7:00 AM                    Pacing    186\n22 Barren           Elf 10:00 AM                    Pacing      8\n23 Barren           Elf  6:00 PM                    Pacing      8\n24  Small         Fairy  7:00 AM                    Pacing    234\n25  Small         Fairy 10:00 AM                    Pacing    340\n26  Small         Fairy  2:00 PM                    Pacing    381\n27  Small         Fairy  6:00 PM                    Pacing    212\n28  Large         Fairy 10:00 AM                   Circles      8\n29  Large         Fairy 10:00 AM                    Pacing     22\n30  Large         Fairy  2:00 PM                    Pacing      7\n31 Barren         Fairy  7:00 AM                    Pacing      6\n32 Barren         Fairy 10:00 AM                    Pacing    396\n33 Barren         Fairy  2:00 PM                    Pacing    132\n34 Barren         Fairy  6:00 PM                    Pacing    111\n35  Small         Ghost  7:00 AM                    Pacing      3\n36  Small        Kraken  7:00 AM                    Pacing      6\n37  Small        Kraken  7:00 AM       Pacing with a hover    790\n38  Small        Kraken 10:00 AM       Pacing with a hover   1204\n39  Small        Kraken 10:00 AM                   Zig zag     77\n40  Small        Kraken  2:00 PM       Pacing with a hover    746\n41  Small        Kraken  2:00 PM                   Zig zag     64\n42 Medium        Kraken 10:00 AM                   Circles     13\n43 Medium        Kraken  2:00 PM                   Circles     22\n44  Large        Kraken  7:00 AM                   Circles      9\n45  Large        Kraken 10:00 AM                    Pacing     77\n46  Large        Kraken  2:00 PM                   Circles     43\n47  Large        Kraken  2:00 PM                    Pacing     41\n48  Large        Kraken  6:00 PM                   Circles      6\n49 Barren        Kraken  7:00 AM                   Circles     15\n50 Barren        Kraken  7:00 AM                   Zig zag     11\n51 Barren        Kraken 10:00 AM                   Circles     41\n52 Barren        Kraken 10:00 AM                    Pacing     28\n53 Barren        Kraken  2:00 PM                    Pacing     21\n54 Barren        Kraken  2:00 PM                   Zig zag     12\n55 Barren        Kraken  6:00 PM                   Circles      7\n56 Barren        Kraken  6:00 PM                    Pacing      0\n57  Small Orange Pendek 10:00 AM                    Pacing      5\n58 Medium Orange Pendek  7:00 AM                    Pacing      8\n59 Medium Orange Pendek 10:00 AM                    Pacing     41\n60 Medium Orange Pendek  2:00 PM                    Pacing      4\n61 Medium Orange Pendek  6:00 PM                    Pacing      3\n62  Large Orange Pendek  7:00 AM                   Circles     15\n63    Jar       Phoenix 10:00 AM                    Pacing      3\n64  Small       Phoenix  7:00 AM                    Pacing      7\n65  Small       Phoenix  2:00 PM                    Pacing     14\n66  Small       Phoenix  6:00 PM                    Pacing      8\n67 Medium       Phoenix  7:00 AM                    Pacing     36\n68 Medium       Phoenix 10:00 AM                    Pacing     19\n69 Medium       Phoenix  2:00 PM                    Pacing    100\n70 Medium       Phoenix  6:00 PM                    Pacing     58\n71  Large       Phoenix  7:00 AM                    Pacing      6\n72  Large       Phoenix 10:00 AM                    Pacing     19\n73  Large       Phoenix  2:00 PM                    Pacing     13\n74  Large       Phoenix  6:00 PM                    Pacing      8\n75 Barren       Phoenix 10:00 AM                   Circles     27\n76 Barren       Phoenix 10:00 AM                    Pacing     18\n77 Barren       Phoenix  2:00 PM           Pace then hover      0\n78 Barren       Phoenix  6:00 PM                   Circles      3\n79 Barren       Phoenix  6:00 PM           Pace then hover      0\n80    Jar        Wizard  2:00 PM                    Pacing      7\n81  Small        Wizard  7:00 AM                    Pacing    681\n82  Small        Wizard 10:00 AM                    Pacing      8\n83  Small        Wizard  6:00 PM                    Pacing     52\n84 Medium        Wizard  7:00 AM                    Pacing     35\n85 Medium        Wizard 10:00 AM                    Pacing     16\n86  Large        Wizard  7:00 AM                    Pacing     35\n87  Large        Wizard 10:00 AM                    Pacing    409\n88  Large        Wizard  2:00 PM                    Pacing    277\n89  Large        Wizard  6:00 PM                    Pacing    185\n90 Barren        Wizard  7:00 AM                    Pacing    527\n91 Barren        Wizard 10:00 AM                    Pacing    472\n92 Barren        Wizard  2:00 PM                    Pacing    432\n93 Barren        Wizard  6:00 PM                    Pacing    641\n```\n:::\n:::\n\n\nI don't think there are enough data to really say something about the number of repetitions. The number of repetitions seems pretty unique to a fish in a certain tank. I don't see an obvious pattern depending on the tank. The interesting thing is that the stereotypic swimming seemed consistent in a tank for a fish (most or all trials of that day with stereotypic swimming). It is a pitty we couldn't calculate the repeatability of the binomial glm of Stereotypic Swimming because it would have been interesting. \n\n:::\n\n# Interaction with Surface\n\n::: {.panel-tabset}\n\n## Distribution \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist1(data$Interation.with.surface)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-37-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\ntable(data$Interation.with.surface==0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n  127   125 \n```\n:::\n:::\n\n\nIdem analysis binary generalised linear models.\n\n## Plot \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(plotInteracting1 <- plot_var_binary(data, \"Interacting.bin\"))\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-38-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n(plotInteracting2 <- plot_var_binary_fish(data, \"Interacting.bin\"))\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-38-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Generalised linear model \n\n\n::: {.cell .column-page layout-align=\"center\"}\n\n```{.r .cell-code}\nmInteracting <- glmmTMB(Interacting.bin ~ Tank + Time + Filter + (1|Fish), data = data, family =binomial)\n\nglmmTMB:::Anova.glmmTMB(mInteracting)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table (Type II Wald chisquare tests)\n\nResponse: Interacting.bin\n         Chisq Df Pr(>Chisq)   \nTank   17.1723  4   0.001789 **\nTime    5.0268  3   0.169846   \nFilter  0.0876  1   0.767253   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\ncalc_contrasts_bin(mInteracting)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         contrast odds.ratio   SE  df null z.ratio p.value asymp.LCL asymp.UCL\n1    jar_vs_small       1.68 0.75 Inf    1    1.15   0.497     0.503     5.580\n2   jar_vs_medium       0.69 0.35 Inf    1   -0.72   0.497     0.174     2.748\n3    jar_vs_large       4.39 2.32 Inf    1    2.80   0.030     1.061    18.167\n4 small_vs_medium       0.41 0.21 Inf    1   -1.74   0.251     0.105     1.625\n5  small_vs_large       2.62 1.36 Inf    1    1.86   0.251     0.651    10.547\n6 medium_vs_large       6.35 3.00 Inf    1    3.92  <0.001     1.783    22.628\n7 large_vs_barren       0.30 0.14 Inf    1   -2.66   0.039     0.086     1.012\n```\n:::\n:::\n\n\nEffect of Tank.\n\n+ Tank. Fish were more likely to interact with the surface during a trial in Jar/Medium compared to Large (not significant for Small). Fish in Jar were 4 times [CI 1, 18] more likely to interact with the surface during a trial than fish in Large, and Fish in Medium were 6 times [CI 2, 23] then fish in Large. In addition, fish were 3 times [CI 1, 12] more likely to interact with a surface during a trial in Barren than in Large. \n\n## Between-fish diff\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmInteracting0 <- glmmTMB(Interacting.bin ~ Tank + Time + Filter, data = data, family =binomial)\nanova(mInteracting0, mInteracting)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData: data\nModels:\nmInteracting0: Interacting.bin ~ Tank + Time + Filter, zi=~0, disp=~1\nmInteracting: Interacting.bin ~ Tank + Time + Filter + (1 | Fish), zi=~0, disp=~1\n              Df    AIC    BIC logLik deviance  Chisq Chi Df Pr(>Chisq)    \nmInteracting0  9 346.41 378.17 -164.2   328.41                             \nmInteracting  10 329.40 364.69 -154.7   309.40 19.008      1  1.302e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nLikelihood ratio test indicates a statistically significant random effect. Meaning that fish behaved differently among each others in terms of interaction with surface. \n\n## Diagnosis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmInteracting_res <- simulateResiduals(mInteracting)\nplot(mInteracting_res)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-41-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplotResiduals(mInteracting_res, form = data$Tank)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-41-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe model seems good.\n\n## Interacting types\n\nJust a plot with the type of interaction depending on the tank. To stick with the analysis, it is a count (count = 1 if the fish performs a certain type of interaction with surface during a trial). \n\nThe second plot groups similar interactions with surface together.\n\n\n::: {.cell .column-page layout-align=\"center\"}\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-42-1.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-42-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n# Nest.building\n\n::: {.panel-tabset}\n\n## Distribution \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist1(data$Nest.building)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-43-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\ntable(data$Nest.building==0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n   51   201 \n```\n:::\n:::\n\n\nThere are 1 trial out of 5 where there was nest building. Analysis with binary generalised model.\n\n## Plot \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(plotNest1 <- plot_var_binary(data, \"Nest.bin\"))\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-44-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n(plotNest2<- plot_var_binary_fish(data, \"Nest.bin\"))\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-44-2.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Generalised linear model \n\n\n::: {.cell .column-page layout-align=\"center\"}\n\n```{.r .cell-code}\nmNest <- glmmTMB(Nest.bin ~ Tank + Time + Filter + (1|Fish), data = data, family =binomial)\n\nglmmTMB:::Anova.glmmTMB(mNest)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table (Type II Wald chisquare tests)\n\nResponse: Nest.bin\n         Chisq Df Pr(>Chisq)   \nTank   10.1022  4   0.038741 * \nTime    7.1655  3   0.066804 . \nFilter 10.3912  1   0.001266 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\ncalc_contrasts_bin(mNest)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         contrast odds.ratio   SE  df null z.ratio p.value asymp.LCL asymp.UCL\n1    jar_vs_small       0.29 0.16 Inf    1   -2.24   0.150     0.065     1.283\n2   jar_vs_medium       0.25 0.16 Inf    1   -2.15   0.158     0.046     1.410\n3    jar_vs_large       0.22 0.14 Inf    1   -2.40   0.116     0.040     1.205\n4 small_vs_medium       0.89 0.50 Inf    1   -0.22  >0.999     0.196     3.992\n5  small_vs_large       0.76 0.42 Inf    1   -0.49  >0.999     0.171     3.398\n6 medium_vs_large       0.86 0.47 Inf    1   -0.27  >0.999     0.196     3.770\n7 large_vs_barren       4.17 2.90 Inf    1    2.05   0.162     0.639    27.143\n```\n:::\n\n```{.r .cell-code}\nemmeans(mNest, ~ Filter, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Filter      prob     SE  df asymp.LCL asymp.UCL\n No-filter 0.2081 0.0621 Inf   0.11154    0.3549\n Filter    0.0234 0.0170 Inf   0.00552    0.0935\n\nResults are averaged over the levels of: Tank, Time \nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n:::\n:::\n\n\nEffect of Tank and Filter.\n+ Tank. Despite a significant effect of Tank, no contrasts were statistically significant. This is usual when you have a weakly significant fixed effect of a factor (0.01 < p-value < 0.05) which has a lot of different levels. In terms of trend, fish in Jar seemed less likely to build a nest compared to Small/Medium/Large. In addition, fish in Barren were less likely to build nest than fish in Large. \n+ Filter. Fish were more likely to build a nest without a filter in their tank.\n\n## Between-fish diff\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmNest0 <- glmmTMB(Nest.bin ~ Tank + Time + Filter, data = data, family =binomial)\nanova(mNest0, mNest)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData: data\nModels:\nmNest0: Nest.bin ~ Tank + Time + Filter, zi=~0, disp=~1\nmNest: Nest.bin ~ Tank + Time + Filter + (1 | Fish), zi=~0, disp=~1\n       Df    AIC    BIC  logLik deviance  Chisq Chi Df Pr(>Chisq)    \nmNest0  9 238.24 270.00 -110.12   220.24                             \nmNest  10 228.68 263.98 -104.34   208.68 11.552      1  0.0006769 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nLikelihood ratio test indicates a statistically significant random effect. Meaning that fish behaved differently among each others in terms of nest building. \n\n## Diagnosis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmNest_res <- simulateResiduals(mNest)\nplot(mNest_res)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-47-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplotResiduals(mNest_res, form = data$Tank)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-47-2.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplotResiduals(mNest_res, form = data$Time)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-47-3.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nplotResiduals(mNest_res, form = data$Filter)\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-47-4.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe model seems good.\n\n:::\n\n# Up and down \n\n::: {.panel-tabset}\n\nResearch question: did fish use differently use the upper part or lower part of their tank depending of the tank type?\n\n## Plot\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(dataUpDown, aes(y = adj.up, x = Tank)) +\n    geom_jitter(alpha = .5, width = 0.05, height=0, color = grey(0.25)) +\n    stat_summary(fun.y = mean,geom = \"point\",colour = \"red\", size = 4)+\n    stat_summary(fun.min = function(x) mean(x) - sd(x), \n                 fun.max = function(x) mean(x) + sd(x), \n                 geom = \"errorbar\",colour = \"red\", width = 0.15)+\n  ylab(\"Time up (sec)\")\n```\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-48-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nIt seems that the tank has an influence on whether fish prefer being on the upper half or lower half of the tank.\n\n## Model\n\nWe can do different models:\n+ Look at the percentage of time spent up of the trial. Fit a beta distribution. Problem: All percentages need to be 0 < perc < 100%. There are trials with 100% so we can't use beta distribution. \n\n+ Look at the count of seconds (how many seconds the fish spend up of the tank). Fit a binomial distribution. Problem: The diagnostics plots were very bad when fitting mUp <- glmmTMB(cbind(up, down) ~ Tank + Time + Filter + (1|Fish), data = dataUpDown, family = binomial)\n\n+ Look simply at the actual time spent up. Fit a normal distribution. The response variable can be adjusted by the fact that the trial were not perfectly 600 sec. $adj.up= \\frac{\\text{time spent up} * 600}{\\text{trial total duration}}$. It is what has been done.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmUp <- lmer(adj.up ~ Tank + Time + Filter + (1|Fish), data = dataUpDown)\nanova(mUp, ddf = \"Kenward-Roger\", type = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nType II Analysis of Variance Table with Kenward-Roger's method\n       Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    \nTank   259014   64753     4 237.13  3.9094 0.0042910 ** \nTime   284189   94730     3 231.06  5.7200 0.0008588 ***\nFilter  74698   74698     1 135.88  4.5105 0.0354999 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\ncalc_contrasts(mUp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         contrast estimate   SE  df t.ratio p.value lower.CL upper.CL\n1    jar_vs_small      -70 25.9 232   -2.72   0.042     -141       -0\n2   jar_vs_medium       33 29.0 243    1.14   0.769      -46      112\n3    jar_vs_large       -3 29.0 243   -0.09   0.926      -81       76\n4 small_vs_medium      103 28.8 243    3.59   0.003       25      182\n5  small_vs_large       68 28.8 243    2.35   0.097      -10      146\n6 medium_vs_large      -36 25.2 231   -1.41   0.635     -104       33\n7 large_vs_barren      -20 25.9 232   -0.78   0.874      -90       50\n```\n:::\n\n```{.r .cell-code}\nemmeans(mUp, ~ Time) # estimated means of time spent swimming depending on the time of the day \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Time     emmean   SE   df lower.CL upper.CL\n 7:00 AM     275 23.9 31.5      227      324\n 10:00 AM    281 23.9 31.5      232      329\n 2:00 PM     225 23.9 31.5      177      274\n 6:00 PM     201 23.9 31.5      152      250\n\nResults are averaged over the levels of: Tank, Filter \nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n:::\n\n```{.r .cell-code}\nemmeans(mUp, ~ Filter) # estimated means of time spent swimming depending on the time of the day\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Filter    emmean   SE   df lower.CL upper.CL\n No-filter    278 20.2 15.4      235      321\n Filter       214 28.2 35.1      156      271\n\nResults are averaged over the levels of: Tank, Time \nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n:::\n:::\n\n\nEffect of Tank, Time and Filter. \n\n+ Tank. The only statistically significant difference is in between Small and Medium: Fish in Small tank spent on average 103 more seconds [25, 181 95% CI] on the upper half of the tank compared to fish in Medium tanks.\n+ Time. Fish spent more time on the upper half of the tank in the morning.\n+ Filter. Fish spent more time on the upper half of the tank with a filter in their tank.\n\n## Diagnosis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm_diagnosis(mUp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"check constant variance over fitted values\"\n```\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-50-1.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Normality of adj.up\"\n```\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-50-2.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Normality random residuals\"\n```\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-50-3.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output-display}\n![](Analysis_files/figure-html/unnamed-chunk-50-4.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe model seems good.\n\n:::\n\n# Conclusion\n\nWhat we can say first is that there is a effect of the Tank on all behaviours, the tank is there having a big influence on the betta's behaviour. Then, it seems that we have three groups for the Jar/Small/Medium/Large\n\n+ Jar with less likely to build a nest and less likely to perform stereotypic swimming compared to the others\n+ Small and Medium\n+ Large with more time swimming, less time resting, more likely to forage and less likely to interact with the surface\n\nAnd Large and Barren are two different groups\n+ Barren with less likely to build a nest\n+ Large with more time swimming, more likely to forage and less likely to interact with the surface\n\nFianlly, we can say that each fish behave pretty uniquely. \n\n# R version \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.3.1 (2023-06-16 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: Australia/Sydney\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices datasets  utils     methods   base     \n\nother attached packages:\n [1] renv_1.0.7          nlme_3.1-162        performance_0.11.0 \n [4] rptR_0.9.22         DHARMa_0.4.6        glmmTMB_1.1.9      \n [7] fitdistrplus_1.1-11 survival_3.5-5      MASS_7.3-60        \n[10] emmeans_1.10.1      lmerTest_3.1-3      lme4_1.1-35.2      \n[13] Matrix_1.6-5        FactoMineR_2.10     RColorBrewer_1.1-3 \n[16] ggforce_0.4.2       ggrepel_0.9.5       ggpubr_0.6.0       \n[19] lubridate_1.9.3     forcats_1.0.0       stringr_1.5.1      \n[22] dplyr_1.1.3         purrr_1.0.2         readr_2.1.5        \n[25] tidyr_1.3.1         tibble_3.2.1        ggplot2_3.5.0      \n[28] tidyverse_2.0.0    \n\nloaded via a namespace (and not attached):\n [1] Rdpack_2.6           rlang_1.1.1          magrittr_2.0.3      \n [4] compiler_4.3.1       mgcv_1.8-42          vctrs_0.6.3         \n [7] pkgconfig_2.0.3      fastmap_1.1.1        backports_1.4.1     \n[10] labeling_0.4.3       utf8_1.2.3           promises_1.3.0      \n[13] rmarkdown_2.26       tzdb_0.4.0           nloptr_2.0.3        \n[16] xfun_0.43            jsonlite_1.8.8       flashClust_1.01-2   \n[19] later_1.3.2          tweenr_2.0.3         broom_1.0.5         \n[22] parallel_4.3.1       cluster_2.1.4        R6_2.5.1            \n[25] gap.datasets_0.0.6   qgam_1.3.4           stringi_1.8.3       \n[28] car_3.1-2            boot_1.3-28.1        numDeriv_2016.8-1.1 \n[31] estimability_1.5     iterators_1.0.14     Rcpp_1.0.11         \n[34] knitr_1.46           httpuv_1.6.15        splines_4.3.1       \n[37] timechange_0.3.0     tidyselect_1.2.1     rstudioapi_0.16.0   \n[40] abind_1.4-5          yaml_2.3.8           codetools_0.2-19    \n[43] doParallel_1.0.17    TMB_1.9.11           plyr_1.8.9          \n[46] lattice_0.21-8       shiny_1.8.1.1        withr_3.0.0         \n[49] coda_0.19-4.1        evaluate_0.23        polyclip_1.10-6     \n[52] pillar_1.9.0         gap_1.5-3            carData_3.0-5       \n[55] foreach_1.5.2        DT_0.33              insight_0.19.10     \n[58] generics_0.1.3       hms_1.1.3            munsell_0.5.1       \n[61] scales_1.3.0         minqa_1.2.6          xtable_1.8-4        \n[64] leaps_3.1            glue_1.6.2           scatterplot3d_0.3-44\n[67] tools_4.3.1          see_0.8.3            ggsignif_0.6.4      \n[70] mvtnorm_1.2-3        grid_4.3.1           rbibutils_2.2.16    \n[73] colorspace_2.1-0     patchwork_1.2.0      cli_3.6.1           \n[76] fansi_1.0.4          gtable_0.3.4         rstatix_0.7.2       \n[79] digest_0.6.35        pbkrtest_0.5.2       htmlwidgets_1.6.4   \n[82] farver_2.1.1         htmltools_0.5.8.1    lifecycle_1.0.4     \n[85] multcompView_0.1-10  mime_0.12           \n```\n:::\n:::\n\n\n:::\n",
    "supporting": [
      "Analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}